# .github/workflows/update_stormtracker.yaml
name: Update Storm Tracker

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 10 AM UTC
  workflow_dispatch:  # Manually triggered

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        repository: nbarjun/stormtracker
        token: ${{ secrets.STORM_TOKEN }}
        path: stormtracker
        
    - name: Run Storm Tracker detection algorithm
      run: |
        cd stormtracker
        source run_stormtracker.sh
        
    - name: Checkout destination repository
      uses: actions/checkout@v3
      with:
        repository: nbarjun/nbarjun.github.io
        token: ${{ secrets.STORM_TOKEN }}
        path: nbarjun.github.io

    - name: Copy file
      run: |
        cp stormtracker/latest_storms.html nbarjun.github.io/files/latest_storms.html

    - name: Commit and push to destination
      run: |
        cd nbarjun.github.io
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add files/latest_storms.html
        git commit -m "Updated latest storms"
        git push
